Error logging 31
google/quota-monitoring-solution pull request #97
Opened 2023-10-20 22:49 UTC by ypenn21

2023-10-20 22:56 UTC, ypenn21 commented on quota-notification/src/main/java/functions/ConfigureAppAlertHelper.java
> +      MDC.put("severity", "CRITICAL");
MDC is to add the severity field back in cloud logging after switching to using log back https://medium.com/google-cloud/java-logging-on-cloud-run-with-stackdriver-9786d6fdbe17

2023-10-20 22:57 UTC, ypenn21 commented on quota-scan/pom.xml
> +    <dependency>
dependencies for logstash and log back

2023-11-28 16:48 UTC, bgood requested changes

2023-11-28 16:48 UTC, bgood commented on terraform/example/new-policy.yaml
I think we need to remove this file from the PR.

2023-11-28 16:48 UTC, bgood commented on terraform/modules/qms/main.tf
> +    command = "gcloud logging sinks update _Default --log-filter=\"NOT LOG_ID('cloudaudit.googleapis.com/access_transparency') AND NOT LOG_ID('externalaudit.googleapis.com/access_transparency') AND N
Why is access transparency included in the exclusion or some examples of what would be excluded by these conditions?

2023-12-26 18:40 UTC, bgood approved these changes

2023-12-26 19:15 UTC, closed without merging