Handle 1 app code many projects. Update README.MD
google/quota-monitoring-solution pull request #99
Opened 2024-02-13 01:59 UTC by ypenn21

Handle 1 app code many projects. Changed Send notification source code for alerting app codes and projects. Update README.MD #99

2024-02-13 22:58 UTC, anuradha-bajpai-google requested changes
Thanks so much Yanni for the PR.  As we discussed, please update the image and add steps to create app level dashboard also.

2024-02-13 23:12 UTC, ypenn21 commented
Following changes need to be made for the PR:
- Use gcpdraw for the image for the consistency with other architecture diagram
- Add steps to create app level dashboard also i.e. add filter with project Ids in the dashboard query.  Currently the dashboard is showing all projects in the org/folder. For app level dashboard, we can add - 'Using the steps from [step#], create the dashboard, and add a SQL filter for projects within the application'.
- Fix lint error

2024-03-05 00:30 UTC, anuradha-bajpai-google approved these changes

2024-03-05 00:30 UTC, merged

2024-03-05 00:34 UTC, anuradha-bajpai-google commented
FR wrt Issue #12 released with this PR! Big Thanks to @ypenn21